name: workflow_triggers

#Eventos push/pr/schechudele 
on:
  push:
    branches:
      - curso-github-actions

  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 8 15 * *'

jobs:

  trigger-push:
    runs-on: ubuntu-latest

    steps:
      - name: Push message
        run: echo "Creaste un push a curso-github-actions"

  trigger-pr:
    runs-on: ubuntu-latest

    steps:
      - name: PR message
        run: echo "Creaste un PR a main"

  trigger-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Cron message
        run: echo "Hoy es quincena"